import * as THREE from "three";
import { ObstacleOctree, Interactable, RotateInteractable, DoorHandleInteractable, ConsumableInteractable, FoodInteractable, DrinkInteractable, SmokeInteractable, DrugInteractable, BeerInteractable, SeatInteractable, MountInteractable } from "./GameSupport.js";

export function applyGamePart5(Game) {
  Object.assign(Game.prototype, {
    spawnSoundWord(text,source,loudness=1,tiny=false,verticalOffset=1.25){const material=new THREE.SpriteMaterial({map:this.getSoundWordTexture(text),transparent:true,depthWrite:false});const word=new THREE.Sprite(material);word.position.copy(source);word.position.y+=verticalOffset;const baseScale=(tiny?.5:1.35)*loudness;word.scale.set(baseScale,baseScale*.375,1);word.userData.life=0;word.userData.baseScale=baseScale;this.scene.add(word);this.soundWords.push(word);},
    updateSoundWords(dt){for(let i=this.soundWords.length-1;i>=0;i--){const word=this.soundWords[i];word.userData.life+=dt;const life=word.userData.life;const grow=1+life*.8;word.scale.set(word.userData.baseScale*grow,word.userData.baseScale*.375*grow,1);word.material.opacity=Math.max(0,1-life/.7);if(life>=.7){this.scene.remove(word);word.material.dispose();this.soundWords.splice(i,1);}}},
    getFootstepWord(position){if(position.y<.02)return "SPLISH";return "tap";},
    updateFootsteps(){if(this.mounted||this.sittingSeat){this.lastFootstepPosition.copy(this.player.getCenter(new THREE.Vector3()));this.footstepDistance=0;return;}const current=this.player.getCenter(new THREE.Vector3());const dx=current.x-this.lastFootstepPosition.x;const dz=current.z-this.lastFootstepPosition.z;const distance=Math.hypot(dx,dz);this.footstepDistance+=distance;this.lastFootstepPosition.copy(current);if(this.footstepDistance>=.9){this.footstepDistance=0;const floorContact=new THREE.Vector3(current.x,.03,current.z);const word=this.getFootstepWord(floorContact);this.spawnSoundWord(word,floorContact,word==="SPLISH"?.5:.35,true,0);}},
    sitOn(seat){this.sittingSeat=seat;const seatPosition=seat.getWorldPosition(new THREE.Vector3());const current=this.player.getCenter(new THREE.Vector3());const destination=new THREE.Vector3(seatPosition.x,1.18,seatPosition.z);this.player.translate(destination.sub(current));},
    leaveSeat(){if(!this.sittingSeat)return;this.sittingSeat=null;},
    buildTouchDebug(){this.touchDebugMarker=new THREE.Mesh(new THREE.SphereGeometry(.12,12,8),new THREE.MeshBasicMaterial({color:0x168cff,depthTest:false}));this.touchDebugMarker.visible=false;this.touchDebugMarker.renderOrder=999;this.scene.add(this.touchDebugMarker);},
    bindTouchDebug(){document.addEventListener("pointerdown",e=>{const ndc=new THREE.Vector2((e.clientX/innerWidth)*2-1,-(e.clientY/innerHeight)*2+1);this.camera.updateMatrixWorld(true);this.touchDebugRaycaster.setFromCamera(ndc,this.camera);const candidates=[];for(const obj of this.scene.children){if(obj===this.touchDebugMarker||obj===this.player.mesh||!obj.visible)continue;if(obj.isMesh)candidates.push(obj);}const hits=this.touchDebugRaycaster.intersectObjects(candidates,false);if(!hits.length){this.touchDebugMarker.visible=false;return;}this.touchDebugMarker.position.copy(hits[0].point);this.touchDebugMarker.visible=true;this.touchDebugUntil=performance.now()+600;},{capture:true});},
    takePhonePhoto(){this.setPhoneOpen(false);this.renderer.render(this.scene,this.camera);const link=document.createElement("a");link.href=this.renderer.domElement.toDataURL("image/png");link.download="crime-theft-otto.png";document.body.appendChild(link);link.click();link.remove();requestAnimationFrame(()=>this.setPhoneOpen(true));},
    fastTravelHome(){if(this.mounted)return;const current=this.player.getCenter(new THREE.Vector3());const destination=new THREE.Vector3(24.5,current.y,10.5);this.player.translate(destination.sub(current));this.pendingInteraction=null;this.interactionPath=[];},
    setPhoneOpen(open){this.phoneOpen=open;this.phonePanel.classList.toggle("open",open);},
    isScreenPointOnRoad(x,y){if(!this.roads.length)return false;const ndc=new THREE.Vector2((x/innerWidth)*2-1,-(y/innerHeight)*2+1);this.camera.updateMatrixWorld(true);this.tapTargetRaycaster.setFromCamera(ndc,this.camera);return this.tapTargetRaycaster.intersectObjects(this.roads,false).length>0;}
  });
}
