import * as THREE from "three";
import { ObstacleOctree, Interactable, RotateInteractable, DoorHandleInteractable, ConsumableInteractable, FoodInteractable, DrinkInteractable, SmokeInteractable, DrugInteractable, BeerInteractable, SeatInteractable, MountInteractable } from "./GameSupport.js";

export function applyGamePart6(Game) {
  Object.assign(Game.prototype, {
    summonOwnCarBehind(){if(!this.ownCar||this.mounted)return;const center=this.player.getCenter(new THREE.Vector3());const heading=this.player.mesh.rotation.y;const forward=new THREE.Vector3(Math.sin(heading),0,Math.cos(heading));const desired=center.clone().addScaledVector(forward,-12);const roadSpacing=80;const roadX=Math.round(desired.x/roadSpacing)*roadSpacing;const roadZ=Math.round(desired.z/roadSpacing)*roadSpacing;const distanceToVertical=Math.abs(desired.x-roadX);const distanceToHorizontal=Math.abs(desired.z-roadZ);if(distanceToVertical<distanceToHorizontal){this.ownCar.position.set(THREE.MathUtils.clamp(roadX,-960,960),0,THREE.MathUtils.clamp(desired.z,-990,990));this.ownCar.userData.heading=forward.z>=0?0:Math.PI;}else{this.ownCar.position.set(THREE.MathUtils.clamp(desired.x,-990,990),0,THREE.MathUtils.clamp(roadZ,-960,960));this.ownCar.userData.heading=forward.x>=0?Math.PI/2:-Math.PI/2;}this.ownCar.rotation.y=this.ownCar.userData.heading;this.ownCar.visible=true;this.ownCar.updateWorldMatrix(true,true);},
    movePlayer(dt){if(this.sittingSeat&&(Math.abs(this.input.moveX)>.001||Math.abs(this.input.moveY)>.001))this.leaveSeat();if(this.sittingSeat)return;const twoHanded=this.input.manualAim;if(!twoHanded)this.cameraRig.yaw-=this.input.moveX*this.walkTurnSpeed*dt;const forward=this.cameraRig.planarForward();const right=this.cameraRig.planarRight();const desired=new THREE.Vector3().addScaledVector(forward,this.input.moveY);if(twoHanded)desired.addScaledVector(right,this.input.moveX);if(desired.lengthSq()>1)desired.normalize();if(desired.lengthSq()>.001){desired.multiplyScalar(this.moveSpeed*dt);this.movePlayerSolid(desired);const facing=Math.atan2(desired.x,desired.z);this.player.mesh.rotation.y=THREE.MathUtils.lerp(this.player.mesh.rotation.y,facing,.2);}else if(!twoHanded&&Math.abs(this.input.moveX)>.001){const faceForward=this.cameraRig.planarForward();const facing=Math.atan2(faceForward.x,faceForward.z);this.player.mesh.rotation.y=THREE.MathUtils.lerp(this.player.mesh.rotation.y,facing,.3);}const center=this.player.getCenter();const minimumY=this.player.bodyHeight*.5;if(center.y<minimumY)this.player.translate(new THREE.Vector3(0,minimumY-center.y,0));},
    createInteractableSparkles(interactable){const count=18;const geometry=new THREE.BufferGeometry();const positions=new Float32Array(count*3);const phases=new Float32Array(count);const speeds=new Float32Array(count);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2;const r=.28+Math.random()*.32;positions[i*3]=Math.cos(a)*r;positions[i*3+1]=Math.random()*1.1;positions[i*3+2]=Math.sin(a)*r;phases[i]=Math.random()*Math.PI*2;speeds[i]=3+Math.random()*5;}geometry.setAttribute("position",new THREE.BufferAttribute(positions,3));const material=new THREE.PointsMaterial({color:0xffffff,size:.09,transparent:true,opacity:1,depthWrite:false,sizeAttenuation:true,vertexColors:true});const colors=new Float32Array(count*3);colors.fill(1);geometry.setAttribute("color",new THREE.BufferAttribute(colors,3));const points=new THREE.Points(geometry,material);points.visible=false;points.renderOrder=1000;points.userData.phases=phases;points.userData.speeds=speeds;this.scene.add(points);this.interactableSparkles.set(interactable,points);},
    updateInteractableSparkles(){const center=this.getControlledCenter(new THREE.Vector3());const now=performance.now()*.001;for(const interactable of this.interactables){const sparkles=this.interactableSparkles.get(interactable);if(!sparkles)continue;if(!interactable.enabled||!interactable.mesh.visible||interactable.isActivelyUsing(this)){sparkles.visible=false;continue;}const p=interactable.getHighlightPosition(this,new THREE.Vector3());const distance=Math.hypot(p.x-center.x,p.z-center.z);sparkles.visible=distance<=5;if(!sparkles.visible)continue;sparkles.position.copy(p);const colors=sparkles.geometry.getAttribute("color");const phases=sparkles.userData.phases;const speeds=sparkles.userData.speeds;for(let i=0;i<colors.count;i++){const light=.15+.85*(.5+.5*Math.sin(phases[i]+now*speeds[i]));colors.setXYZ(i,light,light,light);}colors.needsUpdate=true;}},
    addInteractable(interactable){this.interactables.push(interactable);this.createInteractableSparkles(interactable);return interactable;}
  });
}
